DATASET_PATH: data/amr
DATASET_NAME: amr-bank-struct-v3.0.txt

NAME_TRAIN_DATASET: train
NAME_VALIDATION_DATASET: validation
NAME_TEST_DATASET: test

PRE_PROCESS: custom
PRE_PROCESS_METHOD: pre_process_amr_dataset

FLATTEN: False
INPUT_IDS: meaning_representation
LABELS: human_reference